version: '3'

services:
    application:
        container_name: tweteroo-application

        build:
            context: .
            dockerfile: Dockerfile

        env_file:
            - .env

        ports:
            - "8080:8080"

        depends_on:
            - database

        networks:
            - api

    database:
        image: postgres:15-alpine
        container_name: tweteroo-database

        env_file:
            - .env

        ports:
            - "5432:5432"

        networks:
            - api

        volumes:
            - data:/data/db

networks:
    api:
        driver: bridge

volumes:
    data: