version: '3'

services:
  application:
    container_name: tweteroo-api

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - database

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/tweteroo
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
    image: postgres:15-alpine
    container_name: tweteroo-database

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tweteroo
